### ISSUE TITLE
Only load 4 projects by default; add show more button

### ISSUE THREAD

**Issue by scottgeleas** [scottgeleas/React-Portfolio#11]

**Comment by danmolloy** [comment]
Hi scottgeleas,

I'm happy to help. What do you want to happen when button is clicked? Or just a button that says 'show more' on each tile? 
Dan

**Comment by scottgeleas** [comment]
I have project cards in a two by eight column. I would like to only show 4 initially, then click a button to show 4 more, until everything is shown
